### ISSUE TITLE
Can't run 1.5.1.0, seems like JIT error (but, IANAP)

### ISSUE THREAD

**Issue by ferdjones** [nicehash/NiceHashMiner-Archived#120]
I get this error when I try running 1.5.1.0 after device detection.  If I click continue, it hangs on 'Saving Settings' progress bar, but I can close via the X in UR corner.:

------------ ERROR MESSAGE BELOW ------------

```

See the end of this message for details on invoking 
just-in-time (JIT) debugging instead of this dialog box.

************** Exception Text **************
System.NullReferenceException: Object reference not set to an instance of an object.
   at NiceHashMiner.Config.RebuildGroups()
   at NiceHashMiner.Form1.StartupTimer_Tick(Object sender, EventArgs e)
   at System.Windows.Forms.Timer.OnTick(EventArgs e)
   at System.Windows.Forms.Timer.TimerNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)


************** Loaded Assemblies **************
mscorlib
    Assembly Version: 2.0.0.0
    Win32 Version: 2.0.50727.8689 (QFE.050727-8600)
    CodeBase: file:///C:/Windows/Microsoft.NET/Framework/v2.0.50727/mscorlib.dll
----------------------------------------
NiceHashMiner
    Assembly Version: 1.5.1.0
    Win32 Version: 1.5.1.0
    CodeBase: file:///C:/Users/FerdJones/Desktop/Mining/Nicehash%20Miner/NiceHashMiner.exe
----------------------------------------
System.Windows.Forms
    Assembly Version: 2.0.0.0
    Win32 Version: 2.0.50727.8670 (QFE.050727-8600)
    CodeBase: file:///C:/WINDOWS/assembly/GAC_MSIL/System.Windows.Forms/2.0.0.0__b77a5c561934e089/System.Windows.Forms.dll
----------------------------------------
System
    Assembly Version: 2.0.0.0
    Win32 Version: 2.0.50727.8690 (QFE.050727-8600)
    CodeBase: file:///C:/WINDOWS/assembly/GAC_MSIL/System/2.0.0.0__b77a5c561934e089/System.dll
----------------------------------------
System.Drawing
    Assembly Version: 2.0.0.0
    Win32 Version: 2.0.50727.8681 (QFE.050727-8600)
    CodeBase: file:///C:/WINDOWS/assembly/GAC_MSIL/System.Drawing/2.0.0.0__b03f5f7f11d50a3a/System.Drawing.dll
----------------------------------------
System.Management
    Assembly Version: 2.0.0.0
    Win32 Version: 2.0.50727.8670 (QFE.050727-8600)
    CodeBase: file:///C:/WINDOWS/assembly/GAC_MSIL/System.Management/2.0.0.0__b03f5f7f11d50a3a/System.Management.dll
----------------------------------------
Newtonsoft.Json
    Assembly Version: 7.0.0.0
    Win32 Version: 7.0.1.18622
    CodeBase: file:///C:/Users/FerdJones/Desktop/Mining/Nicehash%20Miner/Newtonsoft.Json.DLL
----------------------------------------
System.Xml
    Assembly Version: 2.0.0.0
    Win32 Version: 2.0.50727.8679 (QFE.050727-8600)
    CodeBase: file:///C:/WINDOWS/assembly/GAC_MSIL/System.Xml/2.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------
System.Data
    Assembly Version: 2.0.0.0
    Win32 Version: 2.0.50727.8677 (QFE.050727-8600)
    CodeBase: file:///C:/WINDOWS/assembly/GAC_32/System.Data/2.0.0.0__b77a5c561934e089/System.Data.dll
----------------------------------------
log4net
    Assembly Version: 1.2.15.0
    Win32 Version: 1.2.15.0
    CodeBase: file:///C:/Users/FerdJones/Desktop/Mining/Nicehash%20Miner/log4net.DLL
----------------------------------------
System.Configuration
    Assembly Version: 2.0.0.0
    Win32 Version: 2.0.50727.8670 (QFE.050727-8600)
    CodeBase: file:///C:/WINDOWS/assembly/GAC_MSIL/System.Configuration/2.0.0.0__b03f5f7f11d50a3a/System.Configuration.dll
----------------------------------------

************** JIT Debugging **************
To enable just-in-time (JIT) debugging, the .config file for this
application or computer (machine.config) must have the
jitDebugging value set in the system.windows.forms section.
The application must also be compiled with debugging
enabled.

For example:

<configuration>
    <system.windows.forms jitDebugging="true" />
</configuration>

When JIT debugging is enabled, any unhandled exception
will be sent to the JIT debugger registered on the computer
rather than be handled by this dialog box.

```

------------ END ERROR MESSAGE ------------

Info:
Windows 10 Pro x64
i7 4770k, 16 GB RAM
nVidia GTX 1080, 980
AMD 380
Both sets of drivers updated to most recent.  

I am only using NiceHashMiner for the nVidia cards, no AMD or CPU.

**Comment by theLosers106** [comment]
Did you copied the config file from previous version?

**Comment by ferdjones** [comment]
Yes.  I guess that maybe I should not do that?

**Comment by theLosers106** [comment]
yup.. you should start with a new config.. in future releases it will auto detect those thing.. but for now you will have to start with an empty config.. please report back on how it goes and close this issue if it is resolved.. thanks (:

**Comment by ferdjones** [comment]
Whelp, that seems to have worked.  Thanks for the help :)

As a side note, I would put that on the page with this release, as I've been copying the config file from previous versions every time I upgrade, and maybe others do to.  Just my $0.02.

**Comment by theLosers106** [comment]
Thanks.. we are planning to include that in the next release..
