### ISSUE TITLE
After re-installing Nvidia drivers "no compatible devices found" on excavator

### ISSUE THREAD

**Issue by AlainCh2** [nicehash/NiceHashMiner-Archived#1526]
After having DDU'd the new Drivers 399.07 and installed afresh the version 385.41 for stability:
The main NiceHash is open, the progress bar stuck forever, in the same position.

As previously: Uninstalled NiceHash - re-downloaded it - re-installed - reboot -

Did it 3 times - Still same problem.

Can somebody help?
I downgraded Nvidia driver from 399.07 > 398.98 > 384.76 > 385.41 for stability. 
(to avoid sudden short black-screens)
I'm running on 385.41 no more black-screens
(downgrading driver was suggested both by Nvidia forum AND Gigabyte Support).

Deleted User/.../roaming/NH 2 ( may be a NH bad config file ?? - no)  - still same problem
Re-installed the Nvidia driver  -  still same problem

Thanks
Alain
![nicehash no compatible](https://user-images.githubusercontent.com/41082160/45035960-88e4ab00-b05b-11e8-8e9a-894d571ea899.PNG)
![system pic with 384 drivers](https://user-images.githubusercontent.com/41082160/45040087-6eafca80-b065-11e8-9d5e-b9825886de4e.PNG)

**Comment by AlainCh2** [comment]
Downloaded and installed Legacy.
It recognize my hardware and it work.

EasyUse NH 2    - is still not working.

Any reason?   Where to find the damaged files/config?

Alain
![legacy](https://user-images.githubusercontent.com/41082160/45044440-6ad57580-b070-11e8-8232-4e2f936148fd.PNG)

**Comment by AlainCh2** [comment]
Legacy dont work anymore on GPU while CPU still mine.

After few minutes with GPU 0 hash or 0 Sol, something crash in W10.
Screen get garbled all over.

Help please.

Alain

**Comment by AlainCh2** [comment]
Application: NiceHashMinerLegacy.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: System.InvalidOperationException
   at System.Windows.Forms.Control.MarshaledInvoke(System.Windows.Forms.Control, System.Delegate, System.Object[], Boolean)
   at System.Windows.Forms.Control.Invoke(System.Delegate, System.Object[])
   at NiceHashMiner.Forms.Form_Benchmark.AddToStatusCheck(NiceHashMiner.Devices.ComputeDevice, NiceHashMiner.Algorithms.Algorithm)
   at NiceHashMiner.Benchmarking.BenchmarkHandler.NextBenchmark()
   at System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object)
   at System.Threading.ThreadHelper.ThreadStart()

**Comment by AlainCh2** [comment]
WOW!

a lot of support on NiceHash ..

great..
Alain

**Comment by choo737** [comment]
Any update for this? I am having the same issue..

**Comment by AlainCh2** [comment]
yes,
I dropped dead the question....
... no more support... they don't even give out money.

Not worth the trouble.

I enjoy gaming now!

Alain

**Comment by weins3** [comment]
delete the new drivers with ddu (display driver unistaller) in safe mode
reinstall the old drivers
its a problem of nvidia drivers, they dont want that user the card for minning, read in google, same problems

**Comment by AlainCh2** [comment]
> 
> 
> delete the new drivers with ddu (display driver unistaller) in safe mode
> reinstall the old drivers
> its a problem of nvidia drivers, they dont want that user the card for minning, read in google, same problems

I suppose people read what is written before posting.... but no....
From the opening of this thread:

"After having DDU'd the new Drivers 399.07 and installed afresh the version 385.41 for stability:
The main NiceHash is open, the progress bar stuck forever, in the same position."

.....

Thanks for a silly answer ... on a silly problem ...  nobody care anymore.

Alain
