### ISSUE TITLE
Miner does not start

### ISSUE THREAD

**Issue by TomskDiver** [nicehash/NiceHashMiner-Archived#266]
I try start nicehashminer.exe, i select language i click OK. Window dissaperar and nothing to do.
In event viewer info:

```
Log Name:   Application
Source:      .NET Runtime
Date:          10.10.2016 16:17:12
Event ID:   1026
Level:       Error
User:  N/A
Computer:     miner-ПК
Description:
Application: NiceHashMiner.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: System.Management.ManagementException
   at System.Management.ManagementException.ThrowWithExtendedInfo(System.Management.ManagementStatus)
   at System.Management.ManagementObjectCollection+ManagementObjectEnumerator.MoveNext()
   at NiceHashMiner.Form_Main..ctor()
   at NiceHashMiner.Program.Main(System.String[])
```

I try reinstall NET Framework and Visual C++ 2013 Redist.

**Comment by TomskDiver** [comment]
It be problem in WMI registry.
