### ISSUE TITLE
Ati 7990 (dual GPU) doesn't work

### ISSUE THREAD

**Issue by spegelius** [nicehash/NiceHashMiner-Archived#293]
I run Windows 7 VM on a Xenserver host. PCI passthrough is enabled, so I can use Nicehasminer. Version 1.6.1.4 works fine, but all 1.7.x versions crash when attempting to run benchmarks. Error:

System.ArgumentException: An item with the same key has already been added.
   at System.ThrowHelper.ThrowArgumentException(ExceptionResource resource)
   at System.Collections.Generic.Dictionary`2.Insert(TKey key, TValue value, Boolean add)
   at NiceHashMiner.Forms.Form_Benchmark.CalcBenchmarkDevicesAlgorithmQueue()
   at NiceHashMiner.Forms.Form_Benchmark..ctor(BenchmarkPerformanceType benchmarkPerformanceType, Boolean autostart, AlgorithmType singleBenchmarkType)
   at NiceHashMiner.Form_Main.buttonBenchmark_Click(Object sender, EventArgs e)
   at System.Windows.Forms.Control.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnMouseUp(MouseEventArgs mevent)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ButtonBase.WndProc(Message& m)
   at System.Windows.Forms.Button.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

Log:
http://pastebin.com/FryKupmG

**Comment by spegelius** [comment]
Some debugging later and it seems that AMD 7990 does not work properly on 1.7.x version, because the two GPUs have same UUID in Nicehasminer context: 
GPU1: PNPDeviceID PCI\VEN_1002&DEV_679B&SUBSYS_32A01682&REV_00\3&267A616A&0&30
GPU2: PNPDeviceID PCI\VEN_1002&DEV_679B&SUBSYS_32A01682&REV_00\3&267A616A&0&38

Seems that Nicehasminer uses only up to 267A616A as device identifier, which causes problems... I added try-catch to the dictionaty add and benchmarking works now for both of the GPUs, but there's only on benchmark result file (benchmark_PCI_VEN_1002&DEV_679B_267A616A.json) and it mines only on GPU #1

**Comment by spegelius** [comment]
Further debugging: both GPUs are on same bus id, which makes the miner to always use same device. Need to rewrite that logic

**Comment by S74nk0** [comment]
Closing this issue. [New issue](https://github.com/nicehash/NiceHashMiner/issues/393) will be opened until we push out a new release. The fix will be most likely available with the new upcoming release.
