### ISSUE TITLE
NHM Fails to launch

### ISSUE THREAD

**Issue by mavericknoob** [nicehash/NiceHashMiner-Archived#856]
I'm getting the Form_loading error on launch when NHM, attempt to pull CPU info appears to be related to the Crypto system.
AMD FX-8350
Windows 10 : Version 10.0.14393 Build 14393
**_See the end of this message for details on invoking
just-in-time (JIT) debugging instead of this dialog box.

************** Exception Text **************
System.InvalidOperationException: This implementation is not part of the Windows Platform FIPS validated cryptographic algorithms.
at System.Security.Cryptography.SHA256Managed..ctor()
at NiceHashMiner.Devices.ComputeDevice.GetUUID(Int32 id, String group, String name, DeviceGroupType deviceGroupType)
at NiceHashMiner.Devices.ComputeDevice..ctor(Int32 id, String group, String name, Int32 threads, UInt64 affinityMask, Int32 CPUCount)
at NiceHashMiner.Devices.ComputeDeviceManager.Query.CPU.QueryCPUs()
at NiceHashMiner.Devices.ComputeDeviceManager.Query.QueryDevices(IMessageNotifier messageNotifier)
at NiceHashMiner.Form_Main.StartupTimer_Tick(Object sender, EventArgs e)
at System.Windows.Forms.Timer.OnTick(EventArgs e)
at System.Windows.Forms.Timer.TimerNativeWindow.WndProc(Message& m)
at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

************** Loaded Assemblies **************
mscorlib
Assembly Version: 2.0.0.0
Win32 Version: 2.0.50727.8745 (WinRel.050727-8700)
CodeBase: file:///C:/Windows/Microsoft.NET/Framework/v2.0.50727/mscorlib.dll

NiceHashMiner
Assembly Version: 1.7.5.10
Win32 Version: 1.7.5.10
CodeBase: file:///D:/NiceHashMiner_v1.7.5.10/NiceHashMiner.exe

System
Assembly Version: 2.0.0.0
Win32 Version: 2.0.50727.8750 (QFE.050727-8700)
CodeBase: file:///C:/Windows/assembly/GAC_MSIL/System/2.0.0.0__b77a5c561934e089/System.dll

Newtonsoft.Json
Assembly Version: 7.0.0.0
Win32 Version: 7.0.1.18622
CodeBase: file:///D:/NiceHashMiner_v1.7.5.10/Newtonsoft.Json.DLL

System.Windows.Forms
Assembly Version: 2.0.0.0
Win32 Version: 2.0.50727.8745 (WinRel.050727-8700)
CodeBase: file:///C:/Windows/assembly/GAC_MSIL/System.Windows.Forms/2.0.0.0__b77a5c561934e089/System.Windows.Forms.dll

System.Drawing
Assembly Version: 2.0.0.0
Win32 Version: 2.0.50727.8745 (WinRel.050727-8700)
CodeBase: file:///C:/Windows/assembly/GAC_MSIL/System.Drawing/2.0.0.0__b03f5f7f11d50a3a/System.Drawing.dll

System.Management
Assembly Version: 2.0.0.0
Win32 Version: 2.0.50727.8758 (QFE.050727-8700)
CodeBase: file:///C:/Windows/assembly/GAC_MSIL/System.Management/2.0.0.0__b03f5f7f11d50a3a/System.Management.dll

System.Xml
Assembly Version: 2.0.0.0
Win32 Version: 2.0.50727.8745 (WinRel.050727-8700)
CodeBase: file:///C:/Windows/assembly/GAC_MSIL/System.Xml/2.0.0.0__b77a5c561934e089/System.Xml.dll

System.Data
Assembly Version: 2.0.0.0
Win32 Version: 2.0.50727.8751 (QFE.050727-8700)
CodeBase: file:///C:/Windows/assembly/GAC_32/System.Data/2.0.0.0__b77a5c561934e089/System.Data.dll

log4net
Assembly Version: 1.2.15.0
Win32 Version: 1.2.15.0
CodeBase: file:///D:/NiceHashMiner_v1.7.5.10/log4net.DLL

System.Configuration
Assembly Version: 2.0.0.0
Win32 Version: 2.0.50727.8745 (WinRel.050727-8700)
CodeBase: file:///C:/Windows/assembly/GAC_MSIL/System.Configuration/2.0.0.0__b03f5f7f11d50a3a/System.Configuration.dll

MessageBoxManager
Assembly Version: 1.0.0.0
Win32 Version: 1.0.0.0
CodeBase: file:///D:/NiceHashMiner_v1.7.5.10/MessageBoxManager.DLL

************** JIT Debugging **************
To enable just-in-time (JIT) debugging, the .config file for this
application or computer (machine.config) must have the
jitDebugging value set in the system.windows.forms section.
The application must also be compiled with debugging
enabled.

For example:

When JIT debugging is enabled, any unhandled exception
will be sent to the JIT debugger registered on the computer
rather than be handled by this dialog box._**

**Comment by mavericknoob** [comment]
NHM fails when Local Security Policy, "Local Security Policy\Security Settings\Local Policies\ Security Options\System cryptography:Use FIPS compliant algorithms for encryption, hashing, and signing" is enabled.

**Comment by S74nk0** [comment]
@mavericknoob this is strange. Your system should have the needed **Windows Platform FIPS validated cryptographic algorithms**. Is this a CPU only system?

**Comment by mavericknoob** [comment]
@S74nk0 no, there are two 980 ti gpus in the system

**Comment by dadatuputi** [comment]
I have the same issue, on a domain box with the GPO enabled. This related issue on another project has some good points on possibly getting around it: https://github.com/KSP-CKAN/CKAN/issues/1497
