### ISSUE TITLE
Not starting :/

### ISSUE THREAD

**Issue by zavage** [nicehash/NiceHashMiner-Archived#89]
[2016-04-20 23:26:40] [INFO] [NICEHASH] Starting up
[2016-04-20 23:26:40] [INFO] [NICEHASH] Total RAM: 8135MB
[2016-04-20 23:26:40] [INFO] [NICEHASH] Page File Size: 1280MB
[2016-04-20 23:26:43] [INFO] [NVIDIA5.x] Exception: System.ComponentModel.Win32Exception: Access is denied
   at System.Diagnostics.Process.StartWithCreateProcess(ProcessStartInfo startInfo)
   at System.Diagnostics.Process.Start()
   at NiceHashMiner.ccminer.QueryCDevs()
[2016-04-20 23:26:47] [INFO] [AMD_OpenCL] Exception: System.ComponentModel.Win32Exception: The system cannot find the file specified
   at System.Diagnostics.Process.StartWithCreateProcess(ProcessStartInfo startInfo)
   at System.Diagnostics.Process.Start()
   at NiceHashMiner.sgminer.QueryCDevs()
[2016-04-20 23:26:53] [INFO] [NICEHASH] Version get
[2016-04-20 23:26:53] [INFO] [NICEHASH] SMA get
[2016-04-20 23:26:54] [INFO] [COINBASE] Bitcoin rate get
[2016-04-20 23:26:54] [INFO] [COINBASE] Current Bitcoin rate: 442.88
[2016-04-20 23:26:54] [INFO] [NICEHASH] Balance get
[2016-04-20 23:26:54] [INFO] [NICEHASH] Setting environment variables
[2016-04-20 23:27:10] [INFO] [NICEHASH] Starting up
[2016-04-20 23:27:10] [INFO] [NICEHASH] Total RAM: 8135MB
[2016-04-20 23:27:10] [INFO] [NICEHASH] Page File Size: 1280MB
[2016-04-20 23:27:10] [INFO] [NVIDIA5.x] Exception: System.ComponentModel.Win32Exception: The system cannot find the file specified
   at System.Diagnostics.Process.StartWithCreateProcess(ProcessStartInfo startInfo)
   at System.Diagnostics.Process.Start()
   at NiceHashMiner.ccminer.QueryCDevs()
[2016-04-20 23:27:12] [INFO] [AMD_OpenCL] Exception: System.ComponentModel.Win32Exception: The system cannot find the file specified
   at System.Diagnostics.Process.StartWithCreateProcess(ProcessStartInfo startInfo)
   at System.Diagnostics.Process.Start()
   at NiceHashMiner.sgminer.QueryCDevs()
[2016-04-20 23:27:12] [INFO] [NICEHASH] Version get
[2016-04-20 23:27:13] [INFO] [NICEHASH] SMA get
[2016-04-20 23:27:13] [INFO] [COINBASE] Bitcoin rate get
[2016-04-20 23:27:13] [INFO] [COINBASE] Current Bitcoin rate: 442.90
[2016-04-20 23:27:13] [INFO] [NICEHASH] Balance get
[2016-04-20 23:27:13] [INFO] [NICEHASH] Setting environment variables
[2016-04-20 23:28:13] [INFO] [NICEHASH] SMA get
[2016-04-20 23:28:14] [INFO] [NICEHASH] Balance get
[2016-04-20 23:34:40] [INFO] [NICEHASH] Starting up
[2016-04-20 23:34:40] [INFO] [NICEHASH] Total RAM: 8135MB
[2016-04-20 23:34:40] [INFO] [NICEHASH] Page File Size: 1280MB
[2016-04-20 23:34:40] [INFO] [NVIDIA5.x] Exception: System.ComponentModel.Win32Exception: The system cannot find the file specified
   at System.Diagnostics.Process.StartWithCreateProcess(ProcessStartInfo startInfo)
   at System.Diagnostics.Process.Start()
   at NiceHashMiner.ccminer.QueryCDevs()
[2016-04-20 23:34:44] [INFO] [AMD_OpenCL] Exception: System.ComponentModel.Win32Exception: The system cannot find the file specified
   at System.Diagnostics.Process.StartWithCreateProcess(ProcessStartInfo startInfo)
   at System.Diagnostics.Process.Start()
   at NiceHashMiner.sgminer.QueryCDevs()
[2016-04-20 23:34:45] [INFO] [NICEHASH] Version get
[2016-04-20 23:34:45] [INFO] [NICEHASH] SMA get
[2016-04-20 23:34:45] [INFO] [COINBASE] Bitcoin rate get
[2016-04-20 23:34:46] [INFO] [COINBASE] Current Bitcoin rate: 442.66
[2016-04-20 23:34:46] [INFO] [NICEHASH] Balance get
[2016-04-20 23:34:46] [INFO] [NICEHASH] Setting environment variables

I see there is a line Access is denied, where i can change it?

**Comment by theLosers106** [comment]
Please make sure that your antivirus did not delete the files.. refer this FAQ first (https://github.com/nicehash/NiceHashMiner#-troubleshooting) and if you still have problem running NiceHashMiner, please don't hesitate to ask.. (:

**Comment by theLosers106** [comment]
Is this issue resolved yet?

**Comment by zavage** [comment]
yes :)

2016-05-17 19:51 GMT+03:00 theLosers106 notifications@github.com:
