### ISSUE TITLE
Unhandled Exception when clicking stop

### ISSUE THREAD

**Issue by CreamyG31337** [nicehash/NiceHashMiner-Archived#9]
This is only happening on a computer with AMD OpenCL mining and only if the mining windows are NOT hidden.
Idle mode won't work with this exception occurring, otherwise you can just click continue to bypass the exception and the stop button works on the 2nd click.

*************\* Exception Text **************
System.ComponentModel.Win32Exception: Access is denied
   at System.Diagnostics.Process.Kill()
   at NiceHashMiner.Miner.Stop()
   at NiceHashMiner.Form1.button2_Click(Object sender, EventArgs e)
   at System.Windows.Forms.Control.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnMouseUp(MouseEventArgs mevent)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ButtonBase.WndProc(Message& m)
   at System.Windows.Forms.Button.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

**Comment by kenshirothefist** [comment]
Resolved in 1.2.1.0.
