### ISSUE TITLE
NHM 1.7.5.13 Win10 System.IO.IOException

### ISSUE THREAD

**Issue by foxwarernd** [nicehash/NiceHashMiner-Archived#982]
Win 10 , CPU Intel i3-4170, GPU Nvidia GTX 750

Nhm removes a tick from the CPU. When installing a check mark on the CPU and starting, an error is flown
![error1](https://user-images.githubusercontent.com/19841581/26846055-45cbe0a6-4b01-11e7-9238-137f6ca39a70.jpg)

Text:
`Подробная информация об использовании оперативной 
(JIT) отладки вместо данного диалогового 
окна содержится в конце этого сообщения.

************** Текст исключения **************
System.IO.IOException: Неверный дескриптор.

   в System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   в System.IO.__ConsoleStream.Write(Byte[] buffer, Int32 offset, Int32 count)
   в System.IO.StreamWriter.Flush(Boolean flushStream, Boolean flushEncoder)
   в System.IO.StreamWriter.Write(Char[] buffer, Int32 index, Int32 count)
   в System.IO.TextWriter.WriteLine(String value)
   в System.IO.TextWriter.SyncTextWriter.WriteLine(String value)
   в NiceHashMiner.Helpers.ConsolePrint(String grp, String text)
   в NiceHashMiner.Miner.Stop_cpu_ccminer_sgminer_nheqminer(MinerStopType willswitch)
   в NiceHashMiner.Miners.excavator._Stop(MinerStopType willswitch)
   в NiceHashMiner.Miner.Stop(MinerStopType willswitch)
   в NiceHashMiner.Miners.Grouping.GroupMiner.End()
   в NiceHashMiner.Miners.MiningSession.StopAllMiners()
   в NiceHashMiner.Miners.MinersManager.StopAllMiners()
   в NiceHashMiner.Form_Main.StopMining()
   в NiceHashMiner.Form_Main.buttonStopMining_Click(Object sender, EventArgs e)
   в System.Windows.Forms.Control.OnClick(EventArgs e)
   в System.Windows.Forms.Button.OnClick(EventArgs e)
   в System.Windows.Forms.Button.OnMouseUp(MouseEventArgs mevent)
   в System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   в System.Windows.Forms.Control.WndProc(Message& m)
   в System.Windows.Forms.ButtonBase.WndProc(Message& m)
   в System.Windows.Forms.Button.WndProc(Message& m)
   в System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   в System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   в System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

************** Загруженные сборки **************
mscorlib
    Версия сборки: 2.0.0.0
    Версия Win32: 2.0.50727.8784 (WinRel.050727-8700)
    CodeBase: file:///C:/Windows/Microsoft.NET/Framework/v2.0.50727/mscorlib.dll
----------------------------------------
NiceHashMiner
    Версия сборки: 1.7.5.13
    Версия Win32: 1.7.5.13
    CodeBase: file:///C:/mining/NiceHashMiner_v1.7.5.13/NiceHashMiner.exe
----------------------------------------
System
    Версия сборки: 2.0.0.0
    Версия Win32: 2.0.50727.8793 (WinRelRS2.050727-8700)
    CodeBase: file:///C:/Windows/assembly/GAC_MSIL/System/2.0.0.0__b77a5c561934e089/System.dll
----------------------------------------
Newtonsoft.Json
    Версия сборки: 7.0.0.0
    Версия Win32: 7.0.1.18622
    CodeBase: file:///C:/mining/NiceHashMiner_v1.7.5.13/Newtonsoft.Json.DLL
----------------------------------------
System.Windows.Forms
    Версия сборки: 2.0.0.0
    Версия Win32: 2.0.50727.8784 (WinRel.050727-8700)
    CodeBase: file:///C:/Windows/assembly/GAC_MSIL/System.Windows.Forms/2.0.0.0__b77a5c561934e089/System.Windows.Forms.dll
----------------------------------------
System.Drawing
    Версия сборки: 2.0.0.0
    Версия Win32: 2.0.50727.8784 (WinRel.050727-8700)
    CodeBase: file:///C:/Windows/assembly/GAC_MSIL/System.Drawing/2.0.0.0__b03f5f7f11d50a3a/System.Drawing.dll
----------------------------------------
System.Management
    Версия сборки: 2.0.0.0
    Версия Win32: 2.0.50727.8794 (WinRelRS2.050727-8700)
    CodeBase: file:///C:/Windows/assembly/GAC_MSIL/System.Management/2.0.0.0__b03f5f7f11d50a3a/System.Management.dll
----------------------------------------
System.Xml
    Версия сборки: 2.0.0.0
    Версия Win32: 2.0.50727.8784 (WinRel.050727-8700)
    CodeBase: file:///C:/Windows/assembly/GAC_MSIL/System.Xml/2.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------
System.Data
    Версия сборки: 2.0.0.0
    Версия Win32: 2.0.50727.8784 (WinRel.050727-8700)
    CodeBase: file:///C:/Windows/assembly/GAC_32/System.Data/2.0.0.0__b77a5c561934e089/System.Data.dll
----------------------------------------
log4net
    Версия сборки: 1.2.15.0
    Версия Win32: 1.2.15.0
    CodeBase: file:///C:/mining/NiceHashMiner_v1.7.5.13/log4net.DLL
----------------------------------------
System.Configuration
    Версия сборки: 2.0.0.0
    Версия Win32: 2.0.50727.8784 (WinRel.050727-8700)
    CodeBase: file:///C:/Windows/assembly/GAC_MSIL/System.Configuration/2.0.0.0__b03f5f7f11d50a3a/System.Configuration.dll
----------------------------------------
MessageBoxManager
    Версия сборки: 1.0.0.0
    Версия Win32: 1.0.0.0
    CodeBase: file:///C:/mining/NiceHashMiner_v1.7.5.13/MessageBoxManager.DLL
----------------------------------------
mscorlib.resources
    Версия сборки: 2.0.0.0
    Версия Win32: 2.0.50727.8784 (WinRel.050727-8700)
    CodeBase: file:///C:/Windows/Microsoft.NET/Framework/v2.0.50727/mscorlib.dll
----------------------------------------
System.Windows.Forms.resources
    Версия сборки: 2.0.0.0
    Версия Win32: 2.0.50727.8784 (WinRel.050727-8700)
    CodeBase: file:///C:/Windows/assembly/GAC_MSIL/System.Windows.Forms.resources/2.0.0.0_ru_b77a5c561934e089/System.Windows.Forms.resources.dll
----------------------------------------

************** Оперативная отладка (JIT) **************
Для подключения оперативной (JIT) отладки файл .config данного
приложения или компьютера (machine.config) должен иметь
значение jitDebugging, установленное в секции system.windows.forms.
Приложение также должно быть скомпилировано с включенной
отладкой.

Например:

<configuration>
    <system.windows.forms jitDebugging="true" />
</configuration>

При включенной отладке JIT любое необрабатываемое исключение
пересылается отладчику JIT, зарегистрированному на данном компьютере,
вместо того чтобы обрабатываться данным диалоговым окном.

`

Log nhm:
[log.txt](https://github.com/nicehash/NiceHashMiner/files/1056081/log.txt)

**Comment by foxwarernd** [comment]
On NHM 1.7.5.12 all work fine

**Comment by foxwarernd** [comment]
The error does not repeat on the OS Win 7. I understand the problems in the dot net framework - which one (s) should be installed?

**Comment by matchsticks** [comment]
Nobody comments you LOL
I have the same problem, nicehash suddenly stops

OS: Win10
GPU: Geforce 980 Ti
CPU: Intel i5-6500
[nicehash error.txt](https://github.com/nicehash/NiceHashMiner/files/1089995/nicehash.error.txt)


See the end of this message for details on invoking 
just-in-time (JIT) debugging instead of this dialog box.

************** Exception Text **************
System.IO.IOException: The handle is invalid.

   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.__ConsoleStream.Write(Byte[] buffer, Int32 offset, Int32 count)
   at System.IO.StreamWriter.Flush(Boolean flushStream, Boolean flushEncoder)
   at System.IO.StreamWriter.Write(Char[] buffer, Int32 index, Int32 count)
   at System.IO.TextWriter.WriteLine(String value)
   at System.IO.TextWriter.SyncTextWriter.WriteLine(String value)
   at NiceHashMiner.Helpers.ConsolePrint(String grp, String text)
   at NiceHashMiner.Miners.Parsing.ExtraLaunchParametersParser.LogParser(String msg)
   at NiceHashMiner.Miners.Parsing.ExtraLaunchParametersParser.Parse(List`1 MiningPairs, List`1 options, Boolean useIfDefaults, List`1 ignoreLogOpions)
   at NiceHashMiner.Miners.Parsing.ExtraLaunchParametersParser.ParseForMiningPairs(List`1 MiningPairs, DeviceType deviceType, Boolean showLog)
   at NiceHashMiner.Miners.ccminer.Start(String url, String btcAdress, String worker)
   at NiceHashMiner.Miners.Grouping.GroupMiner.Start(String miningLocation, String btcAdress, String worker)
   at NiceHashMiner.Miners.MiningSession.SwichMostProfitableGroupUpMethod(Dictionary`2 NiceHashData, Boolean log)
   at NiceHashMiner.Miners.MinersManager.SwichMostProfitableGroupUpMethod(Dictionary`2 NiceHashData)
   at NiceHashMiner.Form_Main.SMAMinerCheck_Tick(Object sender, EventArgs e)
   at System.Windows.Forms.Timer.OnTick(EventArgs e)
   at System.Windows.Forms.Timer.TimerNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)


************** Loaded Assemblies **************
mscorlib
    Assembly Version: 2.0.0.0
    Win32 Version: 2.0.50727.8745 (WinRel.050727-8700)
    CodeBase: file:///C:/Windows/Microsoft.NET/Framework/v2.0.50727/mscorlib.dll
----------------------------------------
NiceHashMiner
    Assembly Version: 1.7.5.13
    Win32 Version: 1.7.5.13
    CodeBase: file:///C:/Users/BatiDesk/Downloads/NiceHashMiner_v1.7.5.13/NiceHashMiner_v1.7.5.13/NiceHashMiner.exe
----------------------------------------
System
    Assembly Version: 2.0.0.0
    Win32 Version: 2.0.50727.8759 (QFE.050727-8700)
    CodeBase: file:///C:/WINDOWS/assembly/GAC_MSIL/System/2.0.0.0__b77a5c561934e089/System.dll
----------------------------------------
Newtonsoft.Json
    Assembly Version: 7.0.0.0
    Win32 Version: 7.0.1.18622
    CodeBase: file:///C:/Users/BatiDesk/Downloads/NiceHashMiner_v1.7.5.13/NiceHashMiner_v1.7.5.13/Newtonsoft.Json.DLL
----------------------------------------
System.Windows.Forms
    Assembly Version: 2.0.0.0
    Win32 Version: 2.0.50727.8745 (WinRel.050727-8700)
    CodeBase: file:///C:/WINDOWS/assembly/GAC_MSIL/System.Windows.Forms/2.0.0.0__b77a5c561934e089/System.Windows.Forms.dll
----------------------------------------
System.Drawing
    Assembly Version: 2.0.0.0
    Win32 Version: 2.0.50727.8745 (WinRel.050727-8700)
    CodeBase: file:///C:/WINDOWS/assembly/GAC_MSIL/System.Drawing/2.0.0.0__b03f5f7f11d50a3a/System.Drawing.dll
----------------------------------------
System.Management
    Assembly Version: 2.0.0.0
    Win32 Version: 2.0.50727.8763 (QFE.050727-8700)
    CodeBase: file:///C:/WINDOWS/assembly/GAC_MSIL/System.Management/2.0.0.0__b03f5f7f11d50a3a/System.Management.dll
----------------------------------------
System.Xml
    Assembly Version: 2.0.0.0
    Win32 Version: 2.0.50727.8745 (WinRel.050727-8700)
    CodeBase: file:///C:/WINDOWS/assembly/GAC_MSIL/System.Xml/2.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------
System.Data
    Assembly Version: 2.0.0.0
    Win32 Version: 2.0.50727.8751 (QFE.050727-8700)
    CodeBase: file:///C:/WINDOWS/assembly/GAC_32/System.Data/2.0.0.0__b77a5c561934e089/System.Data.dll
----------------------------------------
log4net
    Assembly Version: 1.2.15.0
    Win32 Version: 1.2.15.0
    CodeBase: file:///C:/Users/BatiDesk/Downloads/NiceHashMiner_v1.7.5.13/NiceHashMiner_v1.7.5.13/log4net.DLL
----------------------------------------
System.Configuration
    Assembly Version: 2.0.0.0
    Win32 Version: 2.0.50727.8745 (WinRel.050727-8700)
    CodeBase: file:///C:/WINDOWS/assembly/GAC_MSIL/System.Configuration/2.0.0.0__b03f5f7f11d50a3a/System.Configuration.dll
----------------------------------------
MessageBoxManager
    Assembly Version: 1.0.0.0
    Win32 Version: 1.0.0.0
    CodeBase: file:///C:/Users/BatiDesk/Downloads/NiceHashMiner_v1.7.5.13/NiceHashMiner_v1.7.5.13/MessageBoxManager.DLL
----------------------------------------

************** JIT Debugging **************
To enable just-in-time (JIT) debugging, the .config file for this
application or computer (machine.config) must have the
jitDebugging value set in the system.windows.forms section.
The application must also be compiled with debugging
enabled.

For example:

<configuration>
    <system.windows.forms jitDebugging="true" />
</configuration>

When JIT debugging is enabled, any unhandled exception
will be sent to the JIT debugger registered on the computer
rather than be handled by this dialog box.
